# Generated by Django 4.2.14 on 2024-07-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_set_default_clients_and_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.message'),
        ),
    ]
